### ISSUE TITLE
how do we use the code

### ISSUE THREAD

**Issue by AlaaMaz** [Bellafqira/DICTION#1]
Hi, I want to know how to use your code to test the different watermarking techniques exactly, I can see that it's probably in the test script but it's a bit confusing and there are no instructions

**Comment by Bellafqira** [comment]
We have reworked the README.md and run_tests.sh files to include detailed instructions on how to install the environment and run tests for all model watermarking methods. Please refer to the updated README.md for step-by-step guidance on setting up the environment and executing the test scripts. If you have any further questions or run into any issues, feel free to reach out for additional support.
